import "~/styles/globals.css";
import { Rubik } from "next/font/google";
import { headers } from "next/headers";
import { TRPCReactProvider } from "~/trpc/react";

const rubik = Rubik({
  subsets: ["latin"],
});

export const metadata = {
  title: "Quiz App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} bg-ligh_grey bg-[url(/images/pattern-background-mobile-light.svg)] dark:bg-dark_navy dark:bg-[url(/images/pattern-background-mobile-dark.svg)] md:bg-[url(/images/pattern-background-tablet-light.svg)] md:dark:bg-[url(/images/pattern-background-tablet-dark.svg)] xl:bg-[url(/images/pattern-background-desktop-light.svg)] xl:dark:bg-[url(/images/pattern-background-desktop-dark.svg)]`}
      >
        <TRPCReactProvider headers={headers()}>
          <main className="px-6 md:px-16">{children}</main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
